In [1]:
import pandas as pd
dataset=pd.read_csv("50_Startups.csv")

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
# Convert categorical value into numeric value
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [4]:
dataset.head(5)

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0


In [5]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [6]:
independent = dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependent=dataset[['Profit']]

In [7]:
# importing train_test_split library from sklearn.model_selection library collection
# spliting the dataset to train and test with ratio of 70:30 and assign to variable X_train, X_test, y_train and y_test. 
#for industry standard X represents input, y represents output

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent,test_size=0.30, random_state=0)


In [8]:
X_train.head(5)

,R&D Spend,Administration,Marketing Spend,State_Florida,State_New York
7,130298.13,145530.06,323876.68,1,0
14,119943.24,156547.42,256512.92,1,0
45,1000.23,124153.04,1903.93,0,1
48,542.05,51743.15,0.00,0,1
29,65605.48,153032.06,107138.38,0,1


In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X_train

array([[ 1.17644103,  0.84515251,  0.94354978,  2.        , -0.76870611],
       [ 0.96420324,  1.27283565,  0.42738817,  2.        , -0.76870611],
       [-1.47369826,  0.0153175 , -1.52350329, -0.5       ,  1.30088727],
       [-1.48308929, -2.79556363, -1.53809178, -0.5       ,  1.30088727],
       [-0.14952431,  1.13637282, -0.71716495, -0.5       ,  1.30088727],
       [ 0.85312042, -0.04431628,  0.46771725, -0.5       ,  1.30088727],
       [-0.22353674, -0.3151007 , -0.83981652,  2.        , -0.76870611],
       [-0.19454707,  0.21199679, -1.18497259, -0.5       , -0.76870611],
       [ 0.10478723, -0.08388412,  0.48740807, -0.5       , -0.76870611],
       [-1.0096458 , -1.07019473, -0.4040623 , -0.5       , -0.76870611],
       [ 0.06872897, -0.38396487,  0.75036616, -0.5       , -0.76870611],
       [-1.17638797,  0.14067421, -1.26581817, -0.5       ,  1.30088727],
       [ 0.97648631,  0.9689421 ,  0.84958395, -0.5       ,  1.30088727],
       [ 0.39131191,  0.45560401,  0.3

In [12]:
scy=StandardScaler()
y_train = scy.fit_transform(y_train)
y_test = scy.transform(y_test)

In [13]:
y_train

array([[ 1.0584598 ],
       [ 0.52024861],
       [-1.05315815],
       [-1.73325096],
       [-0.21437081],
       [ 0.45781109],
       [-0.23917856],
       [-0.29752752],
       [ 0.38982871],
       [-0.90035675],
       [ 0.19177354],
       [-0.94079847],
       [ 0.97613935],
       [ 0.55988103],
       [-0.06558473],
       [ 1.08725405],
       [ 0.35210595],
       [-0.74362606],
       [-2.22129239],
       [ 1.89633811],
       [ 0.72909058],
       [-0.47139918],
       [-0.03890196],
       [ 1.06705981],
       [-0.03467182],
       [-0.45375209],
       [ 0.02528783],
       [ 0.29180966],
       [ 0.91913743],
       [-0.67932305],
       [-1.41201281],
       [ 1.68965364],
       [ 1.90725975],
       [-1.57315149],
       [-1.04678213]])

In [14]:
# importing SVR library from sklearn.svm library collection
from sklearn.svm import SVR
regressor = SVR(kernel="linear")
# Train the model using fit method and passing both input and output training value 
regressor.fit(X_train,y_train)

,kernel,'linear'
,degree,3
,gamma,'scale'
,coef0,0.0
,tol,0.001
,C,1.0
,epsilon,0.1
,shrinking,True
,cache_size,200
,verbose,False
,max_iter,-1


In [15]:
regressor.coef_

array([[ 9.25245148e-01,  1.26834633e-02,  4.98667431e-02,
        -3.20728881e-05, -7.35650169e-03]])

In [16]:
regressor.n_support_

array([19], dtype=int32)

In [17]:
regressor.support_

array([ 0,  1,  2,  3,  5,  8, 11, 13, 16, 18, 20, 21, 23, 25, 26, 27, 30,
       31, 33], dtype=int32)

In [18]:
regressor.intercept_

array([0.00702089])

In [19]:
y_pred = regressor.predict(X_test)

In [20]:
y_pred[0]

np.float64(-0.11983838519983682)

In [21]:
from sklearn.metrics import r2_score

In [22]:
r_score = r2_score(y_test, y_pred)
r_score

0.9376541575420615

In [23]:
import pickle
filename = "finalized_model_svm2.sav"
pickle.dump(regressor,open(filename,'wb'))

In [24]:
#Verifying the saved model. 
#Load the saved model from the saved file
loaded_model = pickle.load(open("finalized_model_svm2.sav",'rb'))

In [25]:
preinput = sc.transform([[1234,345,4567,0,0]])

In [26]:
preinput

array([[-1.46890682, -4.79078955, -1.50309804, -0.5       , -0.76870611]])

In [27]:
result = loaded_model.predict(preinput)


In [28]:
result

array([-1.4821254])

In [30]:
preoutput = scy.inverse_transform([result])

In [31]:
preoutput

array([[46475.01366199]])